### ISSUE TITLE
Wrong codegen for set with extra constraints

### ISSUE THREAD

**Issue by cathieO** [BoiseState-AdaptLab/omega#6]
Input:
>>> symbolic N,NNZ,row(1),col(1);
>>> S2 := { [n, i, j] : i - row(n) = 0 && j - col(n) = 0 && n >= 0 && i >= 0 && j >= 0 && -n + NNZ - 1 >= 0 && -i + N - 1 >= 0 && -j + N - 1 >= 0 };
>>> codegen(S2);

Output:
```
if (N >= 1) {
  for(t1 = 0; t1 <= NNZ-1; t1++) {
    if (N >= col(t1)+1 && col(t1) >= 0) {
      for(t2 = 0; t2 <= N-1; t2++) {
        if (row(t1) == t2) {
          t3=col(t1);
          s0(t1,t2,t3);
        }
      }
    }
  }
}
```
Desired output:
```
if (N >= 1) {
  for(t1 = 0; t1 <= NNZ-1; t1++) {
     t2 = row(t1);
     t3=col(t1);
      s0(t1,t2,t3);
    }
  }
```

**Comment by cathieO** [comment]
Here is some important information. A different version of Omega is generating different code. Still wrong, but for different reasons.
`Omega+ and CodeGen+ v2.2.3 (built on 12/09/2020)
Copyright (C) 1994-2000 the Omega Project Team
Copyright (C) 2005-2011 Chun Chen
>>> symbolic N,NNZ,row(1),col(1);
>>> S2 := { [n, i, j] : i - row(n) = 0 && j - col(n) = 0 && n >= 0 && i >= 0 && j >= 0 && -n + NNZ - 1 >= 0 && -i + N - 1 >= 0 && -j + N - 1 >= 0 };
>>> codegen(S2);
if (row(t1) >= 0 && col(t1) >= 0 && N >= col(t1)+1 && N >= row(t1)+1) {
  for(t1 = 0; t1 <= NNZ-1; t1++) {
    t2=row(t1);
    t3=col(t1);
    s0(t1,t2,t3);
  }
}`
We should compare the codegen in the two versions

**Comment by cathieO** [comment]
Some more information: This is the I 2-D array created in the codegen constructor.

`stmt: 0 level: 2
{ Sym=[NNZ,N,col(t1),row(t1)] [t1,t2,t3] : row(t1) = t2 && col(t1) = t3 && 0 <= t1 < NNZ && 0 <= t3 < N && 0 <= t2 < N }
stmt: 0 level: 1
{ Sym=[NNZ,N,col(t1),row(t1)] [t1,t2,t3] : t2 = row(t1) && 0 <= t1 < NNZ && 0 <= row(t1) < N && 0 <= col(t1) < N }
stmt: 0 level: 0
{ Sym=[NNZ,N,col(t1),row(t1)] [t1,t2,t3] : 0 <= t1 < NNZ && 0 <= row(t1) < N && 0 <= col(t1) < N }`

This is notable, because you can see that t3 is projected, then t2. During projection t3 is replaced by col(t1) and then it sticks around. Because t3 = col(t1) they should both be removed from the constraints during projection of t3. Similar things are going on for t2. 

I am not sure if we should fix this here, or if we should fix this during codegen.

**Comment by tpops** [comment]
I do understand what you are pointing out here. Projection is supposed to eliminate the variable from the constraint while maintaining constraints associated with that variable. The question is should equality constraint involving such variable be eliminated too? Do we have some proof that we can look at so we can base this on?

**Comment by cathieO** [comment]
So, those constraints come around after doing transitive closure. However, building an iteration space based on symbolic constants seems odd. I think there are 2 problems here. We aren't using the known functionality that CHiLL uses and the for loop on t2 is just wrong.

**Comment by tpops** [comment]
I do not know about CHiLL's known functionality, however, I have been inspecting the CG on both omega repositories. It is a really large codebase and it would take more time than I anticipated to figure things out. 

Maybe it would be great to look at how guards and bounds are computed for each node in the AST. The function is called `recompute ` and it is a part of CG_result which is the base class for CG_loop, CG_split, and CG_leaf.

**Comment by tpops** [comment]
I saw this code section in CG_loop::recompute function, CG.h:957
```cpp 
// check if actual loop is needed                                                                           
std::pair<EQ_Handle, int> result =
            find_simplest_assignment(hull, hull.set_var(level_));           
```

This is interesting because at this point level t2 should have t2=row(t1) and that should be an assignment.

I would check the definition of this function and compare it to the definition of the same function in the previous omega version. I believe if we can successfully work on this then we can move on to the problem with the guard.

**Comment by tpops** [comment]
I replaced the find_simplest_assignment function in the current version of omega with the previous version of omega. Here is the result of codegen.

```cpp
if (N >= 1) {
  for(t1 = 0; t1 <= NNZ-1; t1++) {
    if (N >= col(t1)+1 && row(t1) >= 0 && col(t1) >= 0 && N >= row(t1)+1) {
      t2=row(t1);
      t3=col(t1);
      s0(t1,t2,t3);
    }
  }
}

```

This is very close to what we want. I would go ahead and work on the guard conditions that bound the uninterpreted functions. 
What I plan to do is to discard guards if there is a direct assignment for a certain level, or better still add those constraints to known so that child nodes would know that the conditions have already been satisfied by parent nodes.

**Comment by cathieO** [comment]
Please look at CHiLL, it already has a parameter called known. It doesn't include guards that are included there.

**Comment by tpops** [comment]
Which of the CHiLL's are you referring to? This: https://github.com/CompOpt4Apps/Artifact-DataDepSimplify/blob/master/chill/ or this: https://github.com/CtopCsUtahEdu/chill. I also noticed that all the artifacts have their own chill folder. Which could have been modified just like omega.

**Comment by tpops** [comment]
Hi,

So I ran the following on Omega:
```sh
>>> symbolic N,NNZ,row(1),col(1);
>>> S2 := { [n, i, j] : i - row(n) = 0 && j - col(n) = 0 && n >= 0 && i >= 0 &&
 j >= 0 && -n + NNZ - 1 >= 0 && -i + N - 1 >= 0 && -j + N - 1 >= 0 };
>>> K :=  { [n] : row(n) >= 0  && col(n) >= 0 && N > 0 && row(n) < N && col(n) < N };                                                               
>>> codegen(S2) given K;

```

Here is what I got:

```cpp
for(t1 = 0; t1 <= NNZ-1; t1++) {
  t2=row(t1);
  t3=col(t1);
  s0(t1,t2,t3);
}
```
